export const ROOT_CHANGED = 'ROOT_CHANGED'
export const RECEIVE_USER = 'RECEIVE_USER'
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE'
export const LOGOUT = 'LOGOUT'
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const RECEIVE_PATH = 'RECEIVE_PATH'
export const DELETE_PATH = 'DELETE_PATH'

// MESSAGES
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'

// CHANNELS
export const RECEIVE_CHANNEL = 'RECEIVE_CHANNEL'
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL'
export const SET_LOADING_EARLIER = 'SET_LOADING_EARLIER'

export const RECEIVE_FCM_TOKEN = 'RECEIVE_FCM_TOKEN'
