# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Subs' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crash'

  # Pods for Subs

end

# Auth0 Lock

pod 'Lock', '~> 1.27'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'

pod 'RSKImageCropper'
pod 'QBImagePickerController'
